
# Generated by Django 5.0.6 on 2025-11-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconfig',
            name='saudacao_template',
            field=models.TextField(default='{saudacao} Segue o boleto dos servicos contabeis com Vencimento em {ven} e valor de R$ {va}.'),
        ),
    ]
