# Generated by Django 5.0.6 on 2025-10-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_boleto_codigo_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('', 'Nao informado'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('emitido', 'Emitido'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('erro', 'Erro'), ('atrasado', 'Atrasado')], default='novo', max_length=10),
        ),
    ]
