# Generated by Django 5.0.6 on 2025-10-13 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_identificador', models.CharField(max_length=128, unique=True)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('boleto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to='billing.boleto')),
            ],
            options={
                'ordering': ('-data', '-id'),
            },
        ),
    ]
