# Generated by Django 5.0.6 on 2025-10-13 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_conciliacao_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacaolancamento',
            name='descricao_chave',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ConciliacaoAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_chave', models.CharField(max_length=255, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacao_aliases', to='billing.cliente')),
            ],
            options={
                'ordering': ('descricao_chave',),
            },
        ),
    ]
