# Generated by Django 5.0.6 on 2025-10-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_conciliacao_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saudacao_template', models.TextField(default='Boa noite! Segue o boleto dos servicos contabeis com vencimento em {vencimento} e valor de R$ {valor}.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao de WhatsApp',
                'verbose_name_plural': 'Configuracoes de WhatsApp',
            },
        ),
    ]
