# Generated by Django 5.2.7 on 2025-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_boleto_whatsapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='saudacao_template',
            field=models.TextField(default='{saudacao} Segue o boleto dos serviços contábeis com Vencimento em {ven} e valor de R$ {va}.'),
        ),
    ]
